export default {
  Mathematics: [
    'Algebraic Geometry',
    'Algebraic Topology',
    'Analysis of PDEs',
    'Category Theory',
    'Classical Analysis and ODEs',
    'Combinatorics',
    'Commutative Algebra',
    'Complex Variables',
    'Differential Geometry',
    'Dynamical Systems',
    'Functional Analysis',
    'General Mathematics',
    'General Topology',
    'Geometric Topology',
    'Group Theory',
    'History and Overview',
    'Information Theory',
    'K-Theory and Homology',
    'Logic',
    'Mathematical Physics',
    'Metric Geometry',
    'Number Theory',
    'Numerical Analysis',
    'Operator Algebras',
    'Optimization and Control',
    'Probability',
    'Quantum Algebra',
    'Representation Theory',
    'Rings and Algebras',
    'Spectral Theory',
    'Statistics Theory',
    'Symplectic Geometry'
  ],
  'Computer Science': [
    'Artificial Intelligence',
    'Computation and Language',
    'Computational Complexity',
    'Computational Engineering, Finance, and Science',
    'Computational Geometry',
    'Computer Science and Game Theory',
    'Computer Vision and Pattern Recognition',
    'Computers and Society',
    'Cryptography and Security',
    'Data Structures and Algorithms',
    'Databases',
    'Digital Libraries',
    'Discrete Mathematics',
    'Distributed, Parallel, and Cluster Computing',
    'Emerging Technologies',
    'Formal Languages and Automata Theory',
    'General Literature',
    'Graphics',
    'Hardware Architecture',
    'Human-Computer Interaction',
    'Information Retrieval',
    'Information Theory',
    'Logic in Computer Science',
    'Machine Learning',
    'Mathematical Software',
    'Multiagent Systems',
    'Multimedia',
    'Networking and Internet Architecture',
    'Neural and Evolutionary Computing',
    'Numerical Analysis',
    'Operating Systems',
    'Other Computer Science',
    'Performance',
    'Programming Languages',
    'Robotics',
    'Social and Information Networks',
    'Software Engineering',
    'Sound',
    'Symbolic Computation',
    'Systems and Control'
  ],
  'Quantitative Biology': [
    'Biomolecules',
    'Cell Behavior',
    'Genomics',
    'Molecular Networks',
    'Neurons and Cognition',
    'Other Quantitative Biology',
    'Populations and Evolution',
    'Quantitative Methods',
    'Subcellular Processes',
    'Tissues and Organs'
  ],
  'Quantitative Finance': [
    'Computational Finance',
    'Economics',
    'General Finance',
    'Mathematical Finance',
    'Portfolio Management',
    'Pricing of Securities',
    'Risk Management',
    'Statistical Finance',
    'Trading and Market Microstructure'
  ],
  Statistics: [
    'Applications',
    'Computation',
    'Machine Learning',
    'Methodology',
    'Other Statistics',
    'Statistics Theory'
  ],
  'Electrical Engineering and Systems Science': [
    'Audio and Speech Processing',
    'Image and Video Processing',
    'Signal Processing',
    'Systems and Control'
  ],
  Economics: ['Econometrics', 'General Economics', 'Theoretical Economics']
}
